[deps]
CTBase = "54762871-cc72-4466-b8e8-f6c8b58076cd"
CTDirect = "790bbbee-bee9-49ee-8912-a9de031322d5"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterMermaid = "a078cd44-4d9c-4618-b545-3ab9d77f9177"
HSL = "34c5aeac-e683-54a6-a0e9-6e0fdc586c50"
NLPModelsIpopt = "f4238b75-b362-5c4c-b852-0801c9a21d71"

[compat]
CTBase = "0.15"
CTDirect = "0.13"
Documenter = "1"
DocumenterMermaid = "0.1"
HSL = "0.5"
NLPModelsIpopt = "0.10"
