[deps]
CTBase = "54762871-cc72-4466-b8e8-f6c8b58076cd"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
NLPModelsIpopt = "f4238b75-b362-5c4c-b852-0801c9a21d71"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
